#!/bin/bash

# enregistre l'heure de début
start_time=$(date +%s)


#chemin des fichiers
fichier_csv="Data/data.csv"
fichier_trajet="/home/marzagui/Travail/PROJET/d2/d2.txt"

#tri du fichier data
awk -F ';' '{sum[$6]+=$5} END {for (i in sum) print sum[i],i}' "$fichier_csv" | sort -nr | head -n 10 > $fichier_trajet

# Commande GNUplot
gnuplot -persist <<EOF
set terminal pngcairo enhanced font 'Times New Roman,12' size 800, 640
set output '/home/marzagui/Travail/PROJET/d2/d2.png'
set style fill solid
set xrange [-1:10]  # Adaptez cette plage au nombre de lignes dans votre fichier
set yrange [0:160000]   # Adaptez cette plage à la distance maximale dans vos données
set boxwidth 0.5
set ytics nomirror
set xtics rotate by -45
set format x ""
set title "option -d2"
set ytics 30000 
plot '$fichier_trajet' using (column(0)):1:xtic(sprintf("%s %s", stringcolumn(2), stringcolumn(3))) with boxes lc rgbcolor 'blue' notitle
EOF

end_time=$(date +%s)  # Enregistre l'heure de fin
echo "Temps d'exécution: $((end_time - start_time)) secondes."
