build :
	cd..
	gcc Progc/prog_t.c -o Progc/prog_t
	gcc Progc/prog_s.c -o Progc/prog_s
droit :
	cd..
	chmod 777 Progc/prog_d1.sh
	chmod 777 Progc/prog_d2.sh
	chmod 777 Progc/prog_l.sh
	chmod 777 Progc/prog_t.sh
	chmod 777 Progc/prog_s.sh
	chmod 777 script_principal.sh
run_t : 
	cd..
	./script_principal.sh t
run_d1 :
	cd..
	./script_principal.sh d1
run_d2 :
	cd..
	./script_principal.sh d2	
run_l :
	cd..
	./script_principal.sh l
run_s :
	cd..
	./script_principal.sh s
clean :
	cd..
	rm Progc/prog_t 
	rm Progc/prog_s
help : 
	cd..
	./script_principal.sh h
	
